<a href="https://colab.research.google.com/github/paranthaman2529/machinelearining/blob/main/Copy_of_E8122043Multivarient.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
hiring=pd.read_csv('https://raw.githubusercontent.com/Rhevathi/DATA-SCIENCE/master/ML/2_linear_reg_multivariate/Exercise/hiring.csv')

In [3]:
hiring

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [4]:
hiring.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   experience                  6 non-null      object 
 1   test_score(out of 10)       7 non-null      float64
 2   interview_score(out of 10)  8 non-null      int64  
 3   salary($)                   8 non-null      int64  
dtypes: float64(1), int64(2), object(1)
memory usage: 384.0+ bytes


In [5]:
hiring.isnull().sum()

experience                    2
test_score(out of 10)         1
interview_score(out of 10)    0
salary($)                     0
dtype: int64

In [6]:
hiring['test_score(out of 10)'].median()

8.0

In [7]:
hiring['test_score(out of 10)']=hiring['test_score(out of 10)'].fillna(hiring['test_score(out of 10)'].median())
hiring

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [8]:
hiring.isnull().sum()

experience                    2
test_score(out of 10)         0
interview_score(out of 10)    0
salary($)                     0
dtype: int64

In [9]:
hiring.dropna(inplace=True)

In [10]:
hiring

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [15]:
k=hiring.drop('salary($)',axis=1)

In [17]:
k

experience  test_score(out of 10)  interview_score(out of 10)
2       five                    6.0                           7
3        two                   10.0                          10
4      seven                    9.0                           6
5      three                    7.0                          10
6        ten                    8.0                           7
7     eleven                    7.0                           8

In [18]:
x.experience[x.experience=='five']=5
x.experience[x.experience=='two']=2
x.experience[x.experience=='seven']=7
x.experience[x.experience=='three']=3
x.experience[x.experience=='ten']=10
x.experience[x.experience=='eleven']=11


<ipython-input-18-febf1b3c0b11>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x.experience[x.experience=='five']=5
<ipython-input-18-febf1b3c0b11>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x.experience[x.experience=='two']=2
<ipython-input-18-febf1b3c0b11>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x.experience[x.experience=='seven']=7
<ipython-input-18-febf1b3c0b11>:4: SettingWithCopyWarning: 
A value is trying to be s

In [19]:
x

experience  test_score(out of 10)  interview_score(out of 10)
2          5                    6.0                           7
3          2                   10.0                          10
4          7                    9.0                           6
5          3                    7.0                          10
6         10                    8.0                           7
7         11                    7.0                           8

In [21]:
y=hiring['salary($)']

In [20]:
y

2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary($), dtype: int64

In [22]:
mregmod=linear_model.LinearRegression()
mregmod.fit(x,y)

LinearRegression()

In [23]:
mregmod.coef_

array([2358.88334883, 1712.35809459, 1671.00481704])

In [24]:
mregmod.intercept_

26445.561846812605

In [25]:
mregmod.predict([[2,9,6]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([56600.58029804])

In [26]:
mregmod.predict([[12,10,10]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([88585.79114905])